server.port=9090

spring.datasource.url=jdbc:postgresql://localhost:5432/splitwise
spring.datasource.username=splitwise_user
spring.datasource.password=splitwise_pass

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

jwt.secret=mysupersecuresecretkeymysupersecuresecretkey

spring.data.redis.host=localhost
spring.data.redis.port=6379